language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: required

cache: pip

before_install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools wheel

install:
  - pip install -U .

script:
  - python -c "import navertts"
  - pip install -U .[test]
  - python -m pytest

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
